### ISSUE TITLE
Residence

### ISSUE THREAD

**Issue by AnasChhilif** [AnasChhilif/budgeteer-api#3]
Add a residence entity and all of it's crud, the residence entity should have created_at updated_at deleted_at and should have a one to many constraint with users, one residence can have many users (could change this to many to many later on, not sure yet) a residence should also have a name that should be unique.

**Comment by SaadBeidourii** [comment]
We need to discuss the Cascade type between Residence and Users.
For reference, see: https://www.baeldung.com/jpa-cascade-types
