### ISSUE TITLE
[BUG] Id incrementation

### ISSUE THREAD

**Issue by dabanner** [AnasChhilif/budgeteer-api#6]
when an save entity fails for whatever reason (i tested with unique issue on my end) the id goes with it, so if you try to save an entity that is supposed to have id = 2 and it fails, when you try again and it works, the id = 2 is gone and ur entity will have id = 3, in other words we skip the id = 2, not a big issue but might be interesting to look into in the future.

URGENCY = LOW

**Comment by AnasChhilif** [comment]
Seems to be more of a feature than a bug.
